### ISSUE TITLE
mportError: failed to find libmagic

### ISSUE THREAD

**Issue by qiaoyan** [dongweiming/r#3]
sudo docker logs tucangku_com
Traceback (most recent call last):
  File "/app/app.py", line 4, in <module>
    import magic
  File "/env/local/lib/python2.7/site-packages/magic.py", line 131, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by dongweiming** [comment]
看起来缺少依赖

https://github.com/ahupp/python-magic#dependencies

**Comment by qiaoyan** [comment]
under unbuntu 14.04
apt-get install libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk
