### ISSUE TITLE
 "GET /static/dist/main.css HTTP/1.1" 404 -

### ISSUE THREAD

**Issue by qiaoyan** [dongweiming/r#4]
- Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
- Restarting with stat
  172.17.0.2 - - [31/Oct/2015 12:46:26] "GET / HTTP/1.1" 200 -
  172.17.0.2 - - [31/Oct/2015 12:46:26] "GET /static/dist/main.css HTTP/1.1" 404 -
  172.17.0.2 - - [31/Oct/2015 12:46:27] "GET /static/dist/vendors.js HTTP/1.1" 404 -
  172.17.0.2 - - [31/Oct/2015 12:46:27] "GET /static/dist/index.js HTTP/1.1" 404 -
  172.17.0.2 - - [31/Oct/2015 12:46:27] "GET /static/dist/index.js HTTP/1.1" 404 -

**Comment by dongweiming** [comment]
@qiaoyan oh. i had fixed. you can pull the newest code. and try again. thanks!

**Comment by qiaoyan** [comment]
thanks.
