### ISSUE TITLE
"Table 'p.PasteFile' doesn't exist"

### ISSUE THREAD

**Issue by qiaoyan** [dongweiming/r#5]
## need initiate database and table if not exsit ?

ProgrammingError: (_mysql_exceptions.ProgrammingError) (1146, "Table 'p.PasteFile' doesn't exist") [SQL: u'INSERT INTO `PasteFile` (filename, filehash, `uploadTime`, mimetype, symlink, size) VALUES (%s, %s, %s, %s, %s, %s)'] [parameters: ('Screen Shot 2015-10-29 at 10.58.57 AM.png', '7d9fbd827db8476498238c62e0931ef6.png', datetime.datetime(2015, 11, 1, 12, 49, 16, 668605), 'application/octet-stream', 'kaiQcU', 14736)]

**Comment by dongweiming** [comment]
@qiaoyan i fixed it. you can pull the newest code. and try again. thanks!
